<?php

namespace Novify\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
    public function search($value)
    {
        $queryBuilder = $this
                                     ->createQueryBuilder('a')
                                     ->where('a.artNom LIKE :request')
                                     ->setParameter('request', '%'.$value.'%')
                                     ->getQuery()
                                 ;

        return $queryBuilder->getResult();
    }
}
