<?php

namespace Novify\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
	// public function findAllWithLimit($limit)
	// {
	// 	// return $this->createQueryBuilder('a')->ge
	// }
}
