<?php

namespace Novify\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeArticleRepository extends EntityRepository
{
}
