<?php

namespace Novify\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends EntityRepository
{
    public function findRecipients()
    {
        $qb = $this
            ->getEntityManager()
            ->createQuery(
                'SELECT n.newsMail FROM Novify\ModelBundle\Entity\Newsletter n'
            )
            ->getArrayResult()
        ;

        return $qb;
    }
}
