novify_security:
    resource: "@NovifySecurityBundle/Resources/config/routing.yml"
    prefix:   /
home:
    pattern: /
    defaults:  { _controller: NovifyFrontBundle:Redirecting:redirectHome }
novify_back:
    resource: "@NovifyBackBundle/Resources/config/routing.yml"
    prefix:   /back

novify_front:
    resource: "@NovifyFrontBundle/Resources/config/routing.yml"
    prefix:   /boutique
