novify_front_homepage:
    path:     /
    defaults: { _controller: NovifyFrontBundle:Front:index }

novify_front_login:
    path:     /login
    defaults: { _controller: NovifyFrontBundle:Front:login }

novify_front_panier:
    path:     /panier
    defaults: { _controller: NovifyFrontBundle:Front:panier }

# temporaire
novify_front_view_fiche:
    path:     /fiche
    defaults: { _controller: NovifyFrontBundle:Front:fiche }

novify_front_view_categorie:
    path:     /{categorie}
    defaults: { _controller: NovifyFrontBundle:Front:viewCat }

novify_front_view_souscategorie:
    path:     /{categorie}/{sousCategorie}
    defaults: { _controller: NovifyFrontBundle:Front:viewSousCat }

novify_front_view_one:
    path:     /{categorie}/{sousCategorie}/{id}
    defaults: { _controller: NovifyFrontBundle:Front:viewone }
    # requirements:
        # id: \d+

novify_front_hello:
    path:     /hello/{name}
    defaults: { _controller: NovifyFrontBundle:Front:hello }

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: NovifyFrontBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
