novify_front_homepage:
    path:     /
    defaults: { _controller: NovifyFrontBundle:Front:index }

novify_front_newsletter:
    path:     /newsletter
    defaults: { _controller: NovifyFrontBundle:Front:newsletter }

novify_front_nouveaute:
    path:     /nouveaute
    defaults: { _controller: NovifyFrontBundle:Front:nouveaute }

novify_front_promo:
    path:     /promo
    defaults: { _controller: NovifyFrontBundle:Front:promo }

novify_front_selection:
    path:     /selection
    defaults: { _controller: NovifyFrontBundle:Front:selection }

novify_front_panier:
    path:     /panier
    defaults: { _controller: NovifyFrontBundle:Front:panier }

novify_front_addtopanier:
    path:     /ajouteraupanier/{id}
    defaults: { _controller: NovifyFrontBundle:Front:addToPanier }
    requirements:
        id: \d+

novify_front_removeinpanier:
    path:     /supprimerdanslepanier/{id}
    defaults: { _controller: NovifyFrontBundle:Front:removePanier }
    requirements:
        id: \d+

novify_front_resetpanier:
    path:     /reset-panier/
    defaults: { _controller: NovifyFrontBundle:Front:resetPanier }

# novify_front_commande:
#     path:     /commander
#     defaults: { _controller: NovifyFrontBundle:Front:commande }

novify_front_compte:
    path:     /compte
    defaults: { _controller: NovifyFrontBundle:Front:compte }

novify_front_compte_modif:
    path:     /compte_modif
    defaults: { _controller: NovifyFrontBundle:Front:compteModif }

novify_front_contact:
    path:     /contact
    defaults: { _controller: NovifyFrontBundle:Front:contact }

novify_front_view_categorie:
    path:     /{categorie}
    defaults: { _controller: NovifyFrontBundle:Front:viewCat }

novify_front_view_souscategorie:
    path:     /{categorie}/{sousCategorie}
    defaults: { _controller: NovifyFrontBundle:Front:viewSousCat }

novify_front_view_one:
    path:     /{categorie}/{sousCategorie}/{id}
    defaults: { _controller: NovifyFrontBundle:Front:viewone }
    requirements:
        id: \d+

novify_front_hello:
    path:     /hello/{name}
    defaults: { _controller: NovifyFrontBundle:Front:hello }
