login:
    pattern:   /login
    defaults:  { _controller: NovifySecurityBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

inscription:
    path:     /inscription
    defaults: { _controller: NovifySecurityBundle:Security:inscription }

