novify_back_index:
    path:     /
    defaults: { _controller: NovifyBackBundle:Back:index }

novify_back_article_hello:
    path:     /article/hello/{name}
    defaults: { _controller: NovifyBackBundle:Articles:hello }

novify_back_article_index:
    path:     /article
    defaults: { _controller: NovifyBackBundle:Articles:index }

novify_back_article_add:
    path:     /article/add
    defaults: { _controller: NovifyBackBundle:Articles:add }

novify_back_article_edit:
    path:     /article/edit/{id}
    defaults: { _controller: NovifyBackBundle:Articles:edit }

novify_back_article_remove:
    path:     /article/remove/{id}
    defaults: { _controller: NovifyBackBundle:Articles:remove }

novify_back_categorie_hello:
    path:     /categorie/hello/{name}
    defaults: { _controller: NovifyBackBundle:Categories:hello }

novify_back_categorie_index:
    path:     /categorie
    defaults: { _controller: NovifyBackBundle:Categories:index }

novify_back_categorie_add:
    path:     /categorie/add
    defaults: { _controller: NovifyBackBundle:Categories:add }

novify_back_categorie_edit:
    path:     /categorie/edit/{id}
    defaults: { _controller: NovifyBackBundle:Categories:edit }

novify_back_categorie_remove:
    path:     /categorie/remove/{id}
    defaults: { _controller: NovifyBackBundle:Categories:remove }

novify_back_souscategorie_hello:
    path:     /sous-categorie/hello/{name}
    defaults: { _controller: NovifyBackBundle:SousCategories:hello }

novify_back_souscategorie_index:
    path:     /sous-categorie
    defaults: { _controller: NovifyBackBundle:SousCategories:index }

novify_back_souscategorie_add:
    path:     /sous-categorie/add
    defaults: { _controller: NovifyBackBundle:SousCategories:add }

novify_back_souscategorie_edit:
    path:     /sous-categorie/edit/{id}
    defaults: { _controller: NovifyBackBundle:SousCategories:edit }

novify_back_souscategorie_remove:
    path:     /sous-categorie/remove/{id}
    defaults: { _controller: NovifyBackBundle:SousCategories:remove }

novify_back_utilisateurs_hello:
    path:     /utilisateurs/hello/{name}
    defaults: { _controller: NovifyBackBundle:Utilisateurs:hello }

novify_back_utilisateurs_index:
    path:     /utilisateurs
    defaults: { _controller: NovifyBackBundle:Utilisateurs:index }

novify_back_utilisateurs_add:
    path:     /utilisateurs/add
    defaults: { _controller: NovifyBackBundle:Utilisateurs:add }

novify_back_utilisateurs_edit:
    path:     /utilisateurs/edit/{id}
    defaults: { _controller: NovifyBackBundle:Utilisateurs:edit }

novify_back_utilisateurs_remove:
    path:     /utilisateurs/remove/{id}
    defaults: { _controller: NovifyBackBundle:Utilisateurs:remove }

novify_back_commandes_hello:
    path:     /commandes/hello/{name}
    defaults: { _controller: NovifyBackBundle:Caroussel:hello }

novify_back_commandes_index:
    path:     /commandes
    defaults: { _controller: NovifyBackBundle:Commandes:index }

novify_back_caroussel_hello:
    path:     /caroussel/hello/{name}
    defaults: { _controller: NovifyBackBundle:Caroussel:hello }

novify_back_caroussel_index:
    path:     /caroussel
    defaults: { _controller: NovifyBackBundle:Caroussel:index }

novify_back_caroussel_add:
    path:     /caroussel/add
    defaults: { _controller: NovifyBackBundle:Caroussel:add }

novify_back_caroussel_edit:
    path:     /caroussel/edit/{id}
    defaults: { _controller: NovifyBackBundle:Caroussel:edit }

novify_back_caroussel_remove:
    path:     /caroussel/remove/{id}
    defaults: { _controller: NovifyBackBundle:Caroussel:remove }